### ISSUE TITLE
Is it possible to provide a legacy version for older iOS versions?

### ISSUE THREAD

**Issue by Proaxel** [level3tjg/TwitchAdBlock#16]
I have an iPad mini 2; the final iOS version supported on this device is 12.5.7. I'd like to use it as a mini tv to lurk streams in, but the minimum iOS required on the latest ipa is 14.2. I'm wondering if the adblock capability can be backported to the older versions of the app (specifically v12.0 according to the settings screen)?

**Comment by level3tjg** [comment]
Twitch 12.8.1 is the last version that supports iOS 12 and it doesn't work at all when sideloaded. I would suggest jailbreaking using checkra1n or Chimera (with [chimerafix](https://github.com/mineek/chimerafix/releases)) and installing TwitchAdBlock and TwitchLoginFix (https://level3tjg.me/repo). Ad blocking should still work on 12.8.1 and the login fix is needed to log into the app at all since Twitch has stopped supporting it.

**Comment by level3tjg** [comment]
Not sure why I said this, I just tried it and watching streams works when sideloaded. There are some things that don't work (claiming channel points bonus, following users) but if all you're wanting is to watch streams then it should be fine. I've updated the GitHub workflow to build LTS IPAs that work on iOS 12
